import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Form from '../components/Form/index';

import styles from '../../styles/Home.module.css'

export default function Home() {
  return (

    <>
      <Head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />

        <title>Gabi Lemos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/GartIcon.svg" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
      </Head>

      <div className={styles.container}>

        <span className={styles.uppertext}>OPS... Pedimos desculpas pelo incoveniente,</span>
        <span className={styles.uppertext}>Mas, estamos desenvolvendo algo incrível</span>
        <span className={styles.uppertext}>Deixe seu e-mail para ficar ligado nas novidades.</span>
        <h1 className={styles.title}>Coming <span className={styles.soontext}>soon</span> </h1>
        <div className={styles.colorOverlay}></div>
        <Form></Form>

        <Link href="/links/gartlemos-links">
          <a className={styles.anchor}>Links <i class="fas fa-external-link-alt"></i></a>
        </Link>

      </div>

    </>
  )
}
