import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
   
    <>
    <Head>
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
     
     <title>Gabi Lemos</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1 className={styles.titulo}>Gart - Por Gabi Lemos </h1>
    <span className={styles.bigger}>EM BREVE....</span>
    </>
  )
}
