import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Form from '../components/Form/index';
import Button from '../components/Button';

import styles from '../../styles/Home.module.css'

export default function Home() {
  return (

    <>
      <Head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />

        <title>Gabi Lemos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/GartIcon.svg" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
      </Head>

      <div className={styles.container}>

        <header className={styles.header}>
          <div className={styles.logo}>
            <Image
              src="/images/Gartlemos-logo.svg"
              height={76.97}
              width={180}
              alt="Gartlemos Logo"
              className={styles.image}
            />
          </div>
        </header>
        <main className={styles.main}>
          <div className={styles.textContainer}>
            <h1>Obrigada pela visita!</h1>
            <p>
              Desculpe pelo transtorno,
            </p>
            <p>
              mas estamos construindo algo incrível!
            </p>
            <p>
              Volte em breve.
            </p>
          </div>
          <div className={styles.imgContainer}>
            <Image
              src="/images/creating-bg.svg"
              height={410}
              width={575}
              alt="Home page background"
              className={styles.bgImg}
            />
          </div>
        </main>
        <Link href="/links/gartlemos-links">
          <a className={styles.anchor}>Links <i class="fas fa-external-link-alt"></i></a>
        </Link>
        <div className={styles.bgFooter}>
        
        </div>

      </div>

    </>
  )
}
